version: '3.7'

volumes:
  database:
    external: true

networks:
  net:
    external: true
    driver: bridge

services:

  frontend:
    container_name: hdt_frontend
    restart: always
    build: 
      context: ./frontend
    ports:
      - 3333:3333
    networks:
      - net

  backend:
    container_name: hdt_backend
    restart: always
    build:
      context: ./backend
    ports:
      - 8888:8888
    # volumes:
    #   - ./backend:/usr/src/app:cached
    networks:
      - net
  
  backend_wordcloud:
    container_name: hdt_backend_wordcloud
    restart: always
    build:
      context: ./backend_python
    ports:
      - 8773:8773
    # volumes:
    #   - ./backend_python:/usr/src/app:cached
    networks:
      - net

  # backend iat # 
  backend_iat:
    container_name: iat_backend
    restart: always
    build:
      context: ./backend_iat
    ports:
      - 7878:7878
    # volumes:
    #   -./backend_iat:/usr/src/app:cached
    networks:
      - net

  database:
    container_name: hdt_database
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    networks:
      - net
    
  database-admin:
    container_name: hdt_database_admin
    restart: always
    image: mongo-express
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@database:27017/
      ME_CONFIG_SITE_BASEURL: /mongoadmin/
    ports:
      - 8081:8081
    networks:
      - net

  nginx:
    container_name: nginx
    restart: always
    image: ubuntu/nginx
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - net

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    networks:
      - net

